---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  url: https://helm.cilium.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: "1.17.*"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 30m
  releaseName: cilium
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    image:
      pullPolicy: IfNotPresent
    ipam:
      mode: kubernetes
    l2announcements:
      enabled: true
