---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/cluster-api-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: cluster-api-operator
      version: "0.22.*"
      sourceRef:
        kind: HelmRepository
        name: capi-operator
      interval: 30m
  releaseName: capi-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    infrastructure:
      docker:
        enabled: true
    cert-manager:
      enabled: true
    addon:
      helm:
        name: cluster-api-addon-provider-helm
        namespace: capi-addon-system
        version: v0.3.1
        createNamespace: true
